export const LOAD_INITIAL_THEME_STATE = 'LOAD_INITIAL_THEME_STATE';
export const LOAD_INITIAL_SONG_STATE = 'LOAD_INITIAL_SONG_STATE';

export const SET_SQLITE_SYNC_STATUS_TO_TRUE = 'SET_SQLITE_SYNC_STATUS_TO_TRUE';
export const SET_SQLITE_SYNC_STATUS_TO_FALSE = 'SET_SQLITE_SYNC_STATUS_TO_FALSE';