export const ADD_SONG = 'ADD_SONG';
export const UPDATE_SONG = 'UPDATE_SONG';
export const DELETE_SONG = 'DELETE_SONG';
export const INSERT_SONG = 'INSERT_SONG';
export const DELETE_SONG_FROM_THEMES = 'DELETE_SONG_FROM_THEMES';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export const SET_SONG_SQLITE_SYNC_STATUS_TO_TRUE = 'SET_SONG_SQLITE_SYNC_STATUS_TO_TRUE';
export const SET_SONG_SQLITE_SYNC_STATUS_TO_FALSE = 'SET_SONG_SQLITE_SYNC_STATUS_TO_FALSE';
