export const ADD_THEME = 'ADD_THEME';
export const INSERT_THEME = 'INSERT_THEME';
export const RECEIVE_THEMES = 'RECEIVE_THEMES';
export const DELETE_SONG_FROM_THEMES = 'DELETE_SONG_FROM_THEMES';
export const SET_THEME_SQLITE_SYNC_STATUS_TO_TRUE = 'SET_THEME_SQLITE_SYNC_STATUS_TO_TRUE';
export const SET_THEME_SQLITE_SYNC_STATUS_TO_FALSE = 'SET_THEME_SQLITE_SYNC_STATUS_TO_FALSE';
